/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package com.cnipph.ipc;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.opensymphony.xwork2.ActionSupport;

/**
 * MyEclipse Struts Creation date: 03-09-2007 XDoclet definition:
 */
public class IpcAction extends ActionSupport {

	/**
	 * Logger for this class
	 */
	private static final Logger logger = Logger.getLogger(IpcAction.class);

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		IpcForm ipcForm = (IpcForm) form;
		String txtIpc = null;
		try {
			txtIpc = URLEncoder.encode(ipcForm.getTxtIpc() != null ? ipcForm.getTxtIpc() : "", "UTF-8");
		} catch (UnsupportedEncodingException uee) {
			logger.error(uee.getMessage());
			return new ActionForward("/IPCTree/ipc.jsp");
		}
		if ("0".equals(ipcForm.getRdoLogic()) && ipcForm.getTxtIpc() != null) {
			request.setAttribute("xml", request.getContextPath() + "/ipc/tree.do?rdoLogic=" + ipcForm.getRdoLogic() + "&txtIpc=" + txtIpc);
		} else if ("1".equals(ipcForm.getRdoLogic()) && ipcForm.getTxtIpc() != null) {
			//request.setAttribute("xml", request.getContextPath() + "/ipc/tree.do?rdoLogic=" + ipcForm.getRdoLogic() + "&txtIpc=" + Util.escape(ipcForm.getTxtIpc()));
			request.setAttribute("xml", request.getContextPath() + "/ipc/tree.do?rdoLogic=" + ipcForm.getRdoLogic() + "&txtIpc=" + txtIpc);
		} else {
			ipcForm.setRdoDB("0");
			ipcForm.setRdoLogic("0");
			request.setAttribute("xml", request.getContextPath() + "/ipc/tree.do");
		}
		return new ActionForward("/IPCTree/ipc.jsp");
	}
}