/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package com.cnipph.ipc;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.opensymphony.xwork2.ActionSupport;

/**
 * MyEclipse Struts Creation date: 03-09-2007 XDoclet definition:
 * 
 * @struts.action path="/ipcTree" name="ipcForm" input="/IPCTree/Ipc.jsp" parameter="method" scope="request"
 */
public class IpcTreeAction extends ActionSupport {

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		IpcForm ipcForm = (IpcForm) form;
		IpcHandler ipcHandler = new IpcHandler(request);
		ipcHandler.createXml(ipcForm, response);
		return null;
	}
}