/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cnipr.cniprgz.struts.form;

import javax.servlet.http.HttpServletRequest;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2009
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 751140144726076702L;

	/** password property */
	private String password;

	/** userName property */
	private String userName;
	
	private String isCorpLogin;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
/*	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}*/

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
/*	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}*/

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getIsCorpLogin() {
		return isCorpLogin;
	}

	public void setIsCorpLogin(String isCorpLogin) {
		this.isCorpLogin = isCorpLogin;
	}
}